
CREATE TABLE IF NOT EXISTS JobTemplate();
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS inventoryResource text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS aapInventoryId bigint;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS credentialResource text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS aapHostCredentialId bigint;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS ansibleProjectResource text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS aapProjectId bigint;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS ansiblePlaybooks text[];
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS ansiblePlaybook text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS jobTemplateName text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS jobTemplateId text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS jobTemplateResource text UNIQUE;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS jobTemplateDescription text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS jobType text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS askExtraVarsOnLaunch boolean;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS extraVars jsonb;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS aapTemplateId bigint;

CREATE TABLE IF NOT EXISTS SiteUser();
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userId text UNIQUE;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userEmail text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFirstName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userLastName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFullName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userProfileUrl text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS seeArchived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS siteFontSize text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS siteTheme text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS customerProfileId text;

CREATE TABLE IF NOT EXISTS HostCredential();
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS credentialName text UNIQUE;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS credentialId text UNIQUE;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS credentialResource text UNIQUE;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS credentialDescription text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS aapCredentialId bigint;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS aapCredentialTypeId bigint;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS userName text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS password text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS becomeMethod text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS becomePassword text;

CREATE TABLE IF NOT EXISTS HostInventory();
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS credentialResource text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryName text UNIQUE;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryId text UNIQUE;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryResource text UNIQUE;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryDescription text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS aapInventoryId bigint;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryKind text;

CREATE TABLE IF NOT EXISTS Host();
ALTER TABLE Host ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS inventoryResource text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS aapHostId bigint;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS hostName text UNIQUE;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS ipAddress text UNIQUE;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS hostId text UNIQUE;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS hostResource text UNIQUE;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS hostDescription text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS aapInventoryId bigint;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS inventoryName text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS eventSubscriptions text[];
ALTER TABLE Host ADD COLUMN IF NOT EXISTS tags text[];

CREATE TABLE IF NOT EXISTS AnsibleProject();
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS sourceControlType text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS sourceControlUrl text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS sourceControlBranch text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS ansibleProjectName text UNIQUE;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS ansibleProjectId text UNIQUE;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS ansibleProjectResource text UNIQUE;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS aapProjectId bigint;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS ansibleProjectDescription text UNIQUE;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS ansiblePlaybooks text[];

CREATE TABLE IF NOT EXISTS Project();
ALTER TABLE Project ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS projectName text UNIQUE;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS projectResource text UNIQUE;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS gpuEnabled boolean;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS podRestartCount integer;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS podsRestarting text[];
ALTER TABLE Project ADD COLUMN IF NOT EXISTS podTerminatingCount integer;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS podsTerminating text[];
ALTER TABLE Project ADD COLUMN IF NOT EXISTS fullPvcsCount integer;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS fullPvcs text[];
ALTER TABLE Project ADD COLUMN IF NOT EXISTS namespaceTerminating boolean;

CREATE TABLE IF NOT EXISTS HostCheckCR();
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS changeRequestId text UNIQUE;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS createdByEmail text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS createdByUserId text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS createdByFullName text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS createdVia text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS ownedByEmail text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS ownedByUserId text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS ownedByDisplayName text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS lifecycleState text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS intentState text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS requestedState text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS realizedState text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS aapOrganizationIdChange bigint;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS jobTemplateResourceChange text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS jobTemplateIdChange text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS aapTemplateIdChange bigint;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkNameChange text UNIQUE;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkIdChange text UNIQUE;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkResourceChange text UNIQUE;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkDescriptionChange text UNIQUE;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkNamespaceChange text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkCommandChange text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkIntervalChange integer;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkPublishedChange boolean;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS eventSubscriptionsChange text[];
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS eventHandlersChange text[];
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS jobTemplateResource text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS jobTemplateId text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS aapTemplateId bigint;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkName text UNIQUE;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkId text UNIQUE;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkResource text UNIQUE;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkDescription text UNIQUE;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkNamespace text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkCommand text;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkInterval integer;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS checkPublished boolean;
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS eventSubscriptions text[];
ALTER TABLE HostCheckCR ADD COLUMN IF NOT EXISTS eventHandlers text[];

CREATE TABLE IF NOT EXISTS HostCheck();
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS jobTemplateResource text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS jobTemplateId text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS aapTemplateId bigint;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkName text UNIQUE;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkId text UNIQUE;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkResource text UNIQUE;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkDescription text UNIQUE;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkNamespace text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkCommand text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkInterval integer;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkPublished boolean;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS eventSubscriptions text[];
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS eventHandlers text[];

CREATE TABLE IF NOT EXISTS TenantIntent();
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS tenantName text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS tenantResource text UNIQUE;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS createdByEmail text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS createdByUserId text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS createdByFullName text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS createdVia text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS intentState text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS requestedState text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS realizedState text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS locked boolean;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS hubId text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS clusterName text;
ALTER TABLE TenantIntent ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;

CREATE TABLE IF NOT EXISTS TenantRequested();
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS tenantName text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS requestedNumber integer;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS requestedId text UNIQUE;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS requestedName text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS createdByEmail text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS createdByUserId text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS createdByFullName text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS createdVia text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS intentState text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS requestedState text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS realizedState text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS locked boolean;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS hubId text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS clusterName text;
ALTER TABLE TenantRequested ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;

CREATE TABLE IF NOT EXISTS TenantApproval();
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS tenantName text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS requestedId text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS approvedByEmail text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS approvedByUserId text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS approvedByFullName text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS approved boolean;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS approvalNote text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS approvalName text;
ALTER TABLE TenantApproval ADD COLUMN IF NOT EXISTS approvalId text UNIQUE;

CREATE TABLE IF NOT EXISTS TenantDiscovered();
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS tenantName text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS requestedId text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS tenantResource text UNIQUE;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS discoveredByEmail text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS discoveredByUserId text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS discoveredByFullName text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS discoveredName text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS createdByEmail text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS createdByUserId text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS createdByFullName text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS createdVia text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS intentState text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS requestedState text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS realizedState text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS discoveredState text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS hubId text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS clusterName text;
ALTER TABLE TenantDiscovered ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;

CREATE TABLE IF NOT EXISTS TenantRealized();
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS tenantName text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS requestedId text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS realizedNumber integer;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS realizedByEmail text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS realizedByUserId text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS realizedByFullName text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS realizedId text UNIQUE;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS realizedName text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS createdByEmail text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS createdByUserId text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS createdByFullName text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS createdVia text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS intentState text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS requestedState text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS realizedState text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS locked boolean;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS hubId text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS clusterName text;
ALTER TABLE TenantRealized ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;

CREATE TABLE IF NOT EXISTS TenantProvider();
ALTER TABLE TenantProvider ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE TenantProvider ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE TenantProvider ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE TenantProvider ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE TenantProvider ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE TenantProvider ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE TenantProvider ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE TenantProvider ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE TenantProvider ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE TenantProvider ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE TenantProvider ADD COLUMN IF NOT EXISTS providerName text;
ALTER TABLE TenantProvider ADD COLUMN IF NOT EXISTS providerId text UNIQUE;
ALTER TABLE TenantProvider ADD COLUMN IF NOT EXISTS providerUrl text;

CREATE TABLE IF NOT EXISTS Provider();
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS providerName text;
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS providerUrl text;
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS requestedClientId text;
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS requestedEnvironmentVariable text;
ALTER TABLE Provider ADD COLUMN IF NOT EXISTS providerRequestInstructions text;

CREATE TABLE IF NOT EXISTS ProviderIntent();
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS providerName text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS providerUrl text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS requestedClientId text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS requestedEnvironmentVariable text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS providerRequestInstructions text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS providerId text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS providerResource text UNIQUE;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS createdByEmail text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS createdByUserId text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS createdByFullName text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS createdVia text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS intentState text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS requestedState text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS realizedState text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE ProviderIntent ADD COLUMN IF NOT EXISTS locked boolean;

CREATE TABLE IF NOT EXISTS RequestApproval();
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS approvedByEmail text;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS approvedByUserId text;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS approvedByFullName text;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS approved boolean;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS approvalNote text;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS modelType text;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS modelResource text;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS approvalName text;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS approvalId text UNIQUE;
ALTER TABLE RequestApproval ADD COLUMN IF NOT EXISTS approvalTitle text;

CREATE TABLE IF NOT EXISTS Tenant();
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS hubId text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS clusterName text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;

DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'jobtemplate_tenantresource_tenantintent_fkey') THEN ALTER TABLE JobTemplate ADD CONSTRAINT jobtemplate_tenantresource_tenantintent_fkey FOREIGN KEY(tenantResource) REFERENCES TenantIntent(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'jobtemplate_inventoryresource_hostinventory_fkey') THEN ALTER TABLE JobTemplate ADD CONSTRAINT jobtemplate_inventoryresource_hostinventory_fkey FOREIGN KEY(inventoryResource) REFERENCES HostInventory(inventoryResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'jobtemplate_credentialresource_hostcredential_fkey') THEN ALTER TABLE JobTemplate ADD CONSTRAINT jobtemplate_credentialresource_hostcredential_fkey FOREIGN KEY(credentialResource) REFERENCES HostCredential(credentialResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'jobtemplate_ansibleprojectresource_ansibleproject_fkey') THEN ALTER TABLE JobTemplate ADD CONSTRAINT jobtemplate_ansibleprojectresource_ansibleproject_fkey FOREIGN KEY(ansibleProjectResource) REFERENCES AnsibleProject(ansibleProjectResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'hostcredential_tenantresource_tenantintent_fkey') THEN ALTER TABLE HostCredential ADD CONSTRAINT hostcredential_tenantresource_tenantintent_fkey FOREIGN KEY(tenantResource) REFERENCES TenantIntent(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'hostinventory_tenantresource_tenantintent_fkey') THEN ALTER TABLE HostInventory ADD CONSTRAINT hostinventory_tenantresource_tenantintent_fkey FOREIGN KEY(tenantResource) REFERENCES TenantIntent(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'hostinventory_credentialresource_hostcredential_fkey') THEN ALTER TABLE HostInventory ADD CONSTRAINT hostinventory_credentialresource_hostcredential_fkey FOREIGN KEY(credentialResource) REFERENCES HostCredential(credentialResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'host_tenantresource_tenantintent_fkey') THEN ALTER TABLE Host ADD CONSTRAINT host_tenantresource_tenantintent_fkey FOREIGN KEY(tenantResource) REFERENCES TenantIntent(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'host_inventoryresource_hostinventory_fkey') THEN ALTER TABLE Host ADD CONSTRAINT host_inventoryresource_hostinventory_fkey FOREIGN KEY(inventoryResource) REFERENCES HostInventory(inventoryResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'ansibleproject_tenantresource_tenantintent_fkey') THEN ALTER TABLE AnsibleProject ADD CONSTRAINT ansibleproject_tenantresource_tenantintent_fkey FOREIGN KEY(tenantResource) REFERENCES TenantIntent(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'hostcheckcr_jobtemplateresourcechange_jobtemplate_fkey') THEN ALTER TABLE HostCheckCR ADD CONSTRAINT hostcheckcr_jobtemplateresourcechange_jobtemplate_fkey FOREIGN KEY(jobTemplateResourceChange) REFERENCES JobTemplate(jobTemplateResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'hostcheckcr_tenantresource_tenantintent_fkey') THEN ALTER TABLE HostCheckCR ADD CONSTRAINT hostcheckcr_tenantresource_tenantintent_fkey FOREIGN KEY(tenantResource) REFERENCES TenantIntent(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'hostcheckcr_jobtemplateresource_jobtemplate_fkey') THEN ALTER TABLE HostCheckCR ADD CONSTRAINT hostcheckcr_jobtemplateresource_jobtemplate_fkey FOREIGN KEY(jobTemplateResource) REFERENCES JobTemplate(jobTemplateResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'hostcheck_tenantresource_tenantintent_fkey') THEN ALTER TABLE HostCheck ADD CONSTRAINT hostcheck_tenantresource_tenantintent_fkey FOREIGN KEY(tenantResource) REFERENCES TenantIntent(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'hostcheck_jobtemplateresource_jobtemplate_fkey') THEN ALTER TABLE HostCheck ADD CONSTRAINT hostcheck_jobtemplateresource_jobtemplate_fkey FOREIGN KEY(jobTemplateResource) REFERENCES JobTemplate(jobTemplateResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'tenantrequested_tenantresource_tenantintent_fkey') THEN ALTER TABLE TenantRequested ADD CONSTRAINT tenantrequested_tenantresource_tenantintent_fkey FOREIGN KEY(tenantResource) REFERENCES TenantIntent(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'tenantapproval_requestedid_tenantrequested_fkey') THEN ALTER TABLE TenantApproval ADD CONSTRAINT tenantapproval_requestedid_tenantrequested_fkey FOREIGN KEY(requestedId) REFERENCES TenantRequested(requestedId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'tenantapproval_tenantresource_tenantintent_fkey') THEN ALTER TABLE TenantApproval ADD CONSTRAINT tenantapproval_tenantresource_tenantintent_fkey FOREIGN KEY(tenantResource) REFERENCES TenantIntent(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'tenantdiscovered_requestedid_tenantrequested_fkey') THEN ALTER TABLE TenantDiscovered ADD CONSTRAINT tenantdiscovered_requestedid_tenantrequested_fkey FOREIGN KEY(requestedId) REFERENCES TenantRequested(requestedId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'tenantdiscovered_tenantresource_tenantintent_fkey') THEN ALTER TABLE TenantDiscovered ADD CONSTRAINT tenantdiscovered_tenantresource_tenantintent_fkey FOREIGN KEY(tenantResource) REFERENCES TenantIntent(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'tenantrealized_requestedid_tenantrequested_fkey') THEN ALTER TABLE TenantRealized ADD CONSTRAINT tenantrealized_requestedid_tenantrequested_fkey FOREIGN KEY(requestedId) REFERENCES TenantRequested(requestedId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'tenantrealized_tenantresource_tenantintent_fkey') THEN ALTER TABLE TenantRealized ADD CONSTRAINT tenantrealized_tenantresource_tenantintent_fkey FOREIGN KEY(tenantResource) REFERENCES TenantIntent(tenantResource); END IF; END $$;
