
CREATE TABLE IF NOT EXISTS SiteUser();
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userId text UNIQUE;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userEmail text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFirstName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userLastName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFullName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userProfileUrl text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS seeArchived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS siteFontSize text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS siteTheme text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS customerProfileId text;

CREATE TABLE IF NOT EXISTS Tenant();
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS tenantName text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS tenantResource text UNIQUE;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS pageId text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS tenantDescription text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS hubId text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS clusterName text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;

CREATE TABLE IF NOT EXISTS HostCredential();
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS credentialName text UNIQUE;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS credentialId text UNIQUE;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS credentialResource text UNIQUE;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS credentialDescription text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS aapCredentialId bigint;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS aapCredentialTypeId bigint;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS userName text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS password text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS becomeMethod text;
ALTER TABLE HostCredential ADD COLUMN IF NOT EXISTS becomePassword text;

CREATE TABLE IF NOT EXISTS HostInventory();
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS credentialResource text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryName text UNIQUE;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryId text UNIQUE;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryResource text UNIQUE;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryDescription text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS aapInventoryId bigint;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryKind text;

CREATE TABLE IF NOT EXISTS Host();
ALTER TABLE Host ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS inventoryResource text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS aapHostId bigint;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS hostName text UNIQUE;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS ipAddress text UNIQUE;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS hostId text UNIQUE;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS hostResource text UNIQUE;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS hostDescription text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS aapInventoryId bigint;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS inventoryName text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS eventSubscriptions text[];
ALTER TABLE Host ADD COLUMN IF NOT EXISTS tags text[];

CREATE TABLE IF NOT EXISTS HostCheck();
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS jobTemplateResource text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS jobTemplateId text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS aapTemplateId bigint;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkName text UNIQUE;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkId text UNIQUE;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkResource text UNIQUE;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkDescription text UNIQUE;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkNamespace text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkCommand text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkInterval integer;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkPublished boolean;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS eventSubscriptions text[];
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS eventHandlers text[];

CREATE TABLE IF NOT EXISTS AnsibleProject();
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS sourceControlType text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS sourceControlUrl text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS sourceControlBranch text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS ansibleProjectName text UNIQUE;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS ansibleProjectId text UNIQUE;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS ansibleProjectResource text UNIQUE;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS aapProjectId bigint;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS ansibleProjectDescription text UNIQUE;

CREATE TABLE IF NOT EXISTS JobTemplate();
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS tenantResource text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS inventoryResource text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS aapInventoryId bigint;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS credentialResource text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS aapHostCredentialId bigint;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS ansibleProjectResource text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS aapProjectId bigint;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS ansiblePlaybook text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS jobTemplateName text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS jobTemplateId text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS jobTemplateResource text UNIQUE;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS jobTemplateDescription text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS jobType text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS extraVars jsonb;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS aapTemplateId bigint;

CREATE TABLE IF NOT EXISTS Project();
ALTER TABLE Project ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS projectName text UNIQUE;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS projectResource text UNIQUE;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS gpuEnabled boolean;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS podRestartCount integer;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS podsRestarting text[];
ALTER TABLE Project ADD COLUMN IF NOT EXISTS podTerminatingCount integer;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS podsTerminating text[];
ALTER TABLE Project ADD COLUMN IF NOT EXISTS fullPvcsCount integer;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS fullPvcs text[];
ALTER TABLE Project ADD COLUMN IF NOT EXISTS namespaceTerminating boolean;

DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'hostcredential_tenantresource_tenant_fkey') THEN ALTER TABLE HostCredential ADD CONSTRAINT hostcredential_tenantresource_tenant_fkey FOREIGN KEY(tenantResource) REFERENCES Tenant(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'hostinventory_tenantresource_tenant_fkey') THEN ALTER TABLE HostInventory ADD CONSTRAINT hostinventory_tenantresource_tenant_fkey FOREIGN KEY(tenantResource) REFERENCES Tenant(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'hostinventory_credentialresource_hostcredential_fkey') THEN ALTER TABLE HostInventory ADD CONSTRAINT hostinventory_credentialresource_hostcredential_fkey FOREIGN KEY(credentialResource) REFERENCES HostCredential(credentialResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'host_tenantresource_tenant_fkey') THEN ALTER TABLE Host ADD CONSTRAINT host_tenantresource_tenant_fkey FOREIGN KEY(tenantResource) REFERENCES Tenant(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'host_inventoryresource_hostinventory_fkey') THEN ALTER TABLE Host ADD CONSTRAINT host_inventoryresource_hostinventory_fkey FOREIGN KEY(inventoryResource) REFERENCES HostInventory(inventoryResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'hostcheck_tenantresource_tenant_fkey') THEN ALTER TABLE HostCheck ADD CONSTRAINT hostcheck_tenantresource_tenant_fkey FOREIGN KEY(tenantResource) REFERENCES Tenant(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'hostcheck_jobtemplateresource_jobtemplate_fkey') THEN ALTER TABLE HostCheck ADD CONSTRAINT hostcheck_jobtemplateresource_jobtemplate_fkey FOREIGN KEY(jobTemplateResource) REFERENCES JobTemplate(jobTemplateResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'ansibleproject_tenantresource_tenant_fkey') THEN ALTER TABLE AnsibleProject ADD CONSTRAINT ansibleproject_tenantresource_tenant_fkey FOREIGN KEY(tenantResource) REFERENCES Tenant(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'jobtemplate_tenantresource_tenant_fkey') THEN ALTER TABLE JobTemplate ADD CONSTRAINT jobtemplate_tenantresource_tenant_fkey FOREIGN KEY(tenantResource) REFERENCES Tenant(tenantResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'jobtemplate_inventoryresource_hostinventory_fkey') THEN ALTER TABLE JobTemplate ADD CONSTRAINT jobtemplate_inventoryresource_hostinventory_fkey FOREIGN KEY(inventoryResource) REFERENCES HostInventory(inventoryResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'jobtemplate_credentialresource_hostcredential_fkey') THEN ALTER TABLE JobTemplate ADD CONSTRAINT jobtemplate_credentialresource_hostcredential_fkey FOREIGN KEY(credentialResource) REFERENCES HostCredential(credentialResource); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'jobtemplate_ansibleprojectresource_ansibleproject_fkey') THEN ALTER TABLE JobTemplate ADD CONSTRAINT jobtemplate_ansibleprojectresource_ansibleproject_fkey FOREIGN KEY(ansibleProjectResource) REFERENCES AnsibleProject(ansibleProjectResource); END IF; END $$;
