
CREATE TABLE IF NOT EXISTS SiteUser();
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userId text UNIQUE;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userEmail text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFirstName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userLastName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFullName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userProfileUrl text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS seeArchived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS siteFontSize text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS siteTheme text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS customerProfileId text;

CREATE TABLE IF NOT EXISTS Tenant();
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS tenantName text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS tenantResource text UNIQUE;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS pageId text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS tenantDescription text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS hubId text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS clusterName text;
ALTER TABLE Tenant ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;

CREATE TABLE IF NOT EXISTS AnsibleProject();
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS tenantResource text references Tenant(tenantResource);
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS organizationId text UNIQUE;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS sourceControlType text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS sourceControlUrl text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS sourceControlBranch text;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS ansibleProjectName text UNIQUE;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS ansibleProjectId text UNIQUE;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS aapProjectId bigint;
ALTER TABLE AnsibleProject ADD COLUMN IF NOT EXISTS ansibleProjectDescription text UNIQUE;

CREATE TABLE IF NOT EXISTS JobTemplate();
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS tenantResource text references Tenant(tenantResource);
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS inventoryResource text references HostInventory(inventoryResource);
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS jobTemplateName text UNIQUE;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS jobTemplateId text UNIQUE;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS jobTemplateDescription text UNIQUE;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS jobType text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS ansibleProjectId text references AnsibleProject(ansibleProjectId);
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS ansiblePlaybook text;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS organizationId text UNIQUE;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS aapInventoryId bigint;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS aapProjectId bigint;
ALTER TABLE JobTemplate ADD COLUMN IF NOT EXISTS aapTemplateId bigint;

CREATE TABLE IF NOT EXISTS HostInventory();
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS tenantResource text references Tenant(tenantResource);
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS tenantId text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS aapOrganizationId bigint;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryName text UNIQUE;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryId text UNIQUE;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryResource text UNIQUE;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryDescription text;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS aapInventoryId bigint;
ALTER TABLE HostInventory ADD COLUMN IF NOT EXISTS inventoryKind text;

CREATE TABLE IF NOT EXISTS Host();
ALTER TABLE Host ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS tenantResource text references Tenant(tenantResource);
ALTER TABLE Host ADD COLUMN IF NOT EXISTS inventoryResource text references HostInventory(inventoryResource);
ALTER TABLE Host ADD COLUMN IF NOT EXISTS aapHostId bigint;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS hostName text UNIQUE;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS ipAddress text UNIQUE;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS hostId text UNIQUE;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS hostResource text UNIQUE;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS hostDescription text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS aapInventoryId bigint;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS inventoryName text;
ALTER TABLE Host ADD COLUMN IF NOT EXISTS eventSubscriptions text[];

CREATE TABLE IF NOT EXISTS HostCheck();
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS tenantResource text references Tenant(tenantResource);
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkName text UNIQUE;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkNamespace text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkCommand text;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkInterval integer;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS checkPublished boolean;
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS eventSubscriptions text[];
ALTER TABLE HostCheck ADD COLUMN IF NOT EXISTS eventHandlers text[];

CREATE TABLE IF NOT EXISTS Project();
ALTER TABLE Project ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS projectName text UNIQUE;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS projectResource text UNIQUE;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS gpuEnabled boolean;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS podRestartCount integer;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS podsRestarting text[];
ALTER TABLE Project ADD COLUMN IF NOT EXISTS podTerminatingCount integer;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS podsTerminating text[];
ALTER TABLE Project ADD COLUMN IF NOT EXISTS fullPvcsCount integer;
ALTER TABLE Project ADD COLUMN IF NOT EXISTS fullPvcs text[];
ALTER TABLE Project ADD COLUMN IF NOT EXISTS namespaceTerminating boolean;
