apiVersion: v1
kind: Service
metadata:
  namespace: dcm
  name: dcm
  labels:
    app.kubernetes.io/instance: dcm
    app.kubernetes.io/name: dcm
spec:
  ports:
  - name: http
    port: 10250
    protocol: TCP
    targetPort: 10250
  - name: cluster
    port: 10251
    protocol: TCP
    targetPort: 10251
  selector:
    app: dcm
    app.kubernetes.io/instance: dcm
    app.kubernetes.io/name: dcm
    deployment: dcm
  type: ClusterIP
