apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-pguser-dcm
  namespace: dcm
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: postgres-pguser-dcm
  dataFrom:
    - extract:
        key: dcm/kv/postgres-pguser-dcm
